name: Build, Test, and Publish Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Install dependencies
      run: go mod tidy

    - name: Run tests
      run: go test ./...

  build-push-container:
    # if: github.ref == 'refs/heads/main'
    name: Docker Build and Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Docker Login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      
      - name: docker build
        run: |
          docker build ${{ inputs.working-directory }}/${{secrets.APP_NAME}}/ -t  ${{secrets.DOCKER_USER}}/${{secrets.CONTAINER_IMAGE_NAME}}:${{ github.run_number  }}
      
      - name : docker push
        run: |
          docker push ${{secrets.DOCKER_USER}}/${{secrets.CONTAINER_IMAGE_NAME}}:${{ github.run_number  }}